12-20 14:50:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "NOT"
Unknown data type: "NOT"; SQL statement:
create table WML_MAIL_TEMPLATE(  WTP_SID   integer not null,  WTP_TYPE  integer not null,  WAC_SID   integer,  WTP_NAME  varchar(100) not null,  WTP_TITLE varchar(1000),  WTP_BODY  text,  WTP_ORDER not null,  WTP_AUID  integer not null,  WTP_ADATE timestamp not null,  WTP_EUID  integer not null,  WTP_EDATE timestamp not null,  primary key(WTP_SID)) [50004-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3661)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3524)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5228)
	at org.h2.command.Parser.parseCreate(Parser.java:3813)
	at org.h2.command.Parser.parsePrepared(Parser.java:323)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:170)
	at zigen.plugin.db.ui.jobs.SqlJob.executeUpdate(SqlJob.java:111)
	at zigen.plugin.db.ui.jobs.SqlJob.executeSingleSQL(SqlJob.java:79)
	at zigen.plugin.db.ui.jobs.SqlJob.run(SqlJob.java:40)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
01-08 17:39:33 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: インデックス "SML_SMEIS_INDEX1" はすでに存在します
Index "SML_SMEIS_INDEX1" already exists; SQL statement:
create index SML_SMEIS_INDEX1 on SML_SMEIS(SAC_SID,SMS_JKBN) [42111-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateIndex.update(CreateIndex.java:65)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:234)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
01-27 09:17:04 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: ","
Unknown data type: ","; SQL statement:
create table WML_ADM_CONF
(
  WAD_ACNT_MAKE         integer      not null,
  WAD_ACCT_SENDFORMAT   integer      not null,
  WAD_ACCT_LOG_REGIST   integer      not null,
  WAD_PERMIT_KBN        integer      not null,
  WAD_AUTO_RECEIVE_TIME integer      not null,
  WAD_DISK              integer      not null,
  WAD_DISK_SIZE         integer,
  WAD_DISK_COMP         integer      default 0,
  WAD_DELRECEIVE        integer      not null,
  WAD_AUTORECEIVE       integer      not null,
  WAD_SEND_HOST         varchar(100),
  WAD_SEND_PORT         integer      default 25,
  WAD_SEND_SSL          integer      default 0,
  WAD_RECEIVE_HOST      varchar(100),
  WAD_RECEIVE_PORT      integer      default 110,
  WAD_RECEIVE_SSL       integer      default 0,
  WAD_CHECK_ADDRESS     integer      not null,
  WAD_CHECK_FILE        integer      not null,
  WAD_COMPRESS_FILE     integer      not null,
  WAD_TIMESENT          integer      not null,
  WAD_SEND_LIMIT        integer      not null,
  WAD_SEND_LIMIT_SIZE   integer      not null,
  WAD_BCC               integer      not null,
  WAD_BCC_TH,
  WAD_WARN_DISK         integer      not null,
  WAD_WARN_DISK_TH
) [50004-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3661)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3524)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5228)
	at org.h2.command.Parser.parseCreate(Parser.java:3813)
	at org.h2.command.Parser.parsePrepared(Parser.java:323)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:234)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
01-31 17:31:42 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "ALTER TABLE BBS_FOR_SUM ADD BFS_SIZE BIGINT NOT NOT[*] NULL DEFAULT 0 "; 期待されるステートメント "NULL"
Syntax error in SQL statement "ALTER TABLE BBS_FOR_SUM ADD BFS_SIZE BIGINT NOT NOT[*] NULL DEFAULT 0 "; expected "NULL"; SQL statement:
alter table BBS_FOR_SUM add BFS_SIZE bigint not not null default 0 [42001-171]
01-31 17:31:58 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列名 "BFI_DISK" が重複しています
Duplicate column name "BFI_DISK"; SQL statement:
alter table BBS_FOR_INF add BFI_DISK integer not null default 0 [42121-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:379)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:554)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:310)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:219)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:155)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:170)
	at zigen.plugin.db.ui.jobs.SqlJob.executeUpdate(SqlJob.java:111)
	at zigen.plugin.db.ui.jobs.SqlJob.executeSingleSQL(SqlJob.java:79)
	at zigen.plugin.db.ui.jobs.SqlJob.run(SqlJob.java:40)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
03-11 14:54:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "WML_ACCOUNT" はすでに存在します
Table "WML_ACCOUNT" already exists; SQL statement:
create table WML_ACCOUNT
(
  WAC_SID                integer       not null,
  WAC_TYPE               integer       not null,
  USR_SID                integer,
  WAC_NAME               varchar(100)  not null,
  WAC_ADDRESS            varchar(256)  not null,
  WAC_SEND_HOST          varchar(100)  not null,
  WAC_SEND_PORT          integer       not null,
  WAC_SEND_USER          varchar(100),
  WAC_SEND_PASS          varchar(100),
  WAC_SEND_SSL           integer       not null,
  WAC_RECEIVE_TYPE       integer       not null,
  WAC_RECEIVE_HOST       varchar(100)  not null,
  WAC_RECEIVE_PORT       integer       not null,
  WAC_RECEIVE_USER       varchar(100)  not null,
  WAC_RECEIVE_PASS       varchar(100)  not null,
  WAC_RECEIVE_SSL        integer       not null,
  WAC_DISK               integer       not null,
  WAC_DISK_SIZE          integer       not null,
  WAC_BIKO               varchar(1000),
  WAC_ORGANIZATION       varchar(100),
  WAC_SIGN               varchar(1000),
  WAC_SIGN_POINT_KBN     integer       not null,
  WAC_SIGN_DSP_KBN       integer       not null,
  WAC_AUTOTO             varchar(100),
  WAC_AUTOCC             varchar(100),
  WAC_AUTOBCC            varchar(100),
  WAC_DELRECEIVE         integer       not null,
  WAC_RERECEIVE          integer       not null,
  WAC_APOP               integer       not null,
  WAC_SMTP_AUTH          integer       not null,
  WAC_POPBSMTP           integer       not null,
  WAC_ENCODE_SEND        integer       not null,
  WAC_AUTORECEIVE        integer       not null,
  WAC_SEND_MAILTYPE      integer       not null,
  WAC_RECEIVE_DATE       timestamp,
  WAC_JKBN               integer       not null,
  WAC_AUTO_RECEIVE_TIME  integer       not null,
  WAC_THEME              integer       not null,
  WAC_CHECK_ADDRESS      integer       not null,
  WAC_CHECK_FILE         integer       not null,
  WAC_COMPRESS_FILE      integer       not null,
  WAC_TIMESENT           integer       not null,
  WAC_QUOTES             integer       not null,
  WAC_DISK_SPS           integer       not null,
  primary key(WAC_SID)
) [42101-171]
05-12 13:57:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: インデックス "WML_LABEL_RELATION_INDEX1" が見つかりません
Index "WML_LABEL_RELATION_INDEX1" not found; SQL statement:
drop index WML_LABEL_RELATION_INDEX1 [42112-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropIndex.update(DropIndex.java:48)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at zigen.plugin.db.core.SQLInvoker.execute(SQLInvoker.java:195)
	at zigen.plugin.db.ui.jobs.SqlExecJob.execute(SqlExecJob.java:359)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:201)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
05-12 13:57:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: インデックス "WML_SENDADDRESS_INDEX1" はすでに存在します
Index "WML_SENDADDRESS_INDEX1" already exists; SQL statement:
create index WML_SENDADDRESS_INDEX1 on WML_SENDADDRESS(WAC_SID,WSA_TYPE) [42111-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateIndex.update(CreateIndex.java:65)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:234)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
09-29 15:42:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "("
Unknown data type: "("; SQL statement:
alter table BBS_FOR_INF add BFI_LIMIT_ON (4) not null default 1 [50004-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3661)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3524)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5000)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4839)
	at org.h2.command.Parser.parseAlter(Parser.java:4322)
	at org.h2.command.Parser.parsePrepared(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at zigen.plugin.db.core.SQLInvoker.execute(SQLInvoker.java:195)
	at zigen.plugin.db.ui.jobs.SqlExecJob.execute(SqlExecJob.java:359)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:201)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
09-29 15:42:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "("
Unknown data type: "("; SQL statement:
alter table BBS_FOR_INF add BFI_LIMIT_ON (4) not null default 1 [50004-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3661)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3524)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5000)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4839)
	at org.h2.command.Parser.parseAlter(Parser.java:4322)
	at org.h2.command.Parser.parsePrepared(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at zigen.plugin.db.core.SQLInvoker.execute(SQLInvoker.java:195)
	at zigen.plugin.db.ui.jobs.SqlExecJob.execute(SqlExecJob.java:359)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:201)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
09-29 17:24:03 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列名 "BFI_LIMIT_ON" が重複しています
Duplicate column name "BFI_LIMIT_ON"; SQL statement:
alter table BBS_FOR_INF add BFI_LIMIT_ON integer not null default 1 [42121-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:379)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:554)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:310)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:219)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:155)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at zigen.plugin.db.core.SQLInvoker.execute(SQLInvoker.java:195)
	at zigen.plugin.db.ui.jobs.SqlExecJob.execute(SqlExecJob.java:359)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:201)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-06 15:36:01 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "REATE[*] INDEX BBS_WRITE_LOG_COUNT_INDEX1 ON BBS_WRITE_LOG_COUNT(BWL_WRT_DATE) "; 期待されるステートメント "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, {"
Syntax error in SQL statement "REATE[*] INDEX BBS_WRITE_LOG_COUNT_INDEX1 ON BBS_WRITE_LOG_COUNT(BWL_WRT_DATE) "; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, {"; SQL statement:
reate index BBS_WRITE_LOG_COUNT_INDEX1 on BBS_WRITE_LOG_COUNT(BWL_WRT_DATE) [42001-171]
10-10 14:24:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ENQ_QUE_MAIN" はすでに存在します
Table "ENQ_QUE_MAIN" already exists; SQL statement:
create table ENQ_QUE_MAIN
(
        EMN_SID         bigint          not null,
        EQM_SEQ         integer         not null,
        EQM_DSP_SEC     integer                 ,
        EQM_QUE_SEC     varchar(10)             ,
        EQM_QUESTION    varchar(100)            ,
        EQM_QUE_KBN     integer                 ,
        EQM_REQUIRE     integer                 ,
        EQM_OTHER       integer                 ,
        EQM_DESC        text                    ,
        EQM_DESC_PLAIN  text                    ,
        EQM_ATTACH_KBN  integer                 ,
        EQM_ATTACH_ID   varchar(100)            ,
        EQM_ATTACH_NAME varchar(100)            ,
        EQM_ATTACH_POS  integer                 ,
        EQM_LINE_KBN    integer                 ,
        EQM_GRF_KBN     integer                 ,
        EQM_APID        varchar(20)     not null,
        EQM_AUID        integer         not null,
        EQM_ADATE       timestamp       not null,
        EQM_EPID        varchar(20)     not null,
        EQM_EUID        integer         not null,
        EQM_EDATE       timestamp       not null,

        primary key (EMN_SID, EQM_SEQ)
) [42101-171]
10-10 15:01:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMM_VER_INFO" が見つかりません
Table "CMM_VER_INFO" not found; SQL statement:
select * from CMM_VER_INFO [42102-171]
10-10 15:02:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMM_VER_INFO" が見つかりません
Table "CMM_VER_INFO" not found; SQL statement:
select * from CMM_VER_INFO [42102-171]
10-10 15:04:11 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set VER_VERSION=4.5.0 [22018-171]
10-10 15:05:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "VER_VERSION" が見つかりません
Table "VER_VERSION" not found; SQL statement:
update VER_VERSION set CMN_VER_INFO=4.5.0 [42102-171]
10-10 15:06:06 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "VER_VERSION" が見つかりません
Table "VER_VERSION" not found; SQL statement:
update VER_VERSION set CMN_VER_INFO="4.5.0" [42102-171]
10-10 15:06:35 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set VER_VERSION=4.5.0 [22018-171]
10-10 15:06:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set VER_VERSION=4.5.0 [22018-171]
10-10 15:06:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION="4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:09:19 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT COUNT(*) FROM PUBLIC.CMN_VER_INFO [50200-171]
10-10 15:09:58 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set VER_VERSION=4.5.0 [22018-171]
10-10 15:10:22 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION="4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:10:57 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set 4.5.0 [22018-171]
10-10 15:11:29 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT * FROM PUBLIC.CMN_VER_INFO  WHERE VER_VERSION = ? [50200-171]
10-10 15:11:46 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT COUNT(*) FROM PUBLIC.CMN_VER_INFO [50200-171]
10-10 15:11:58 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set 4.5.0 [22018-171]
10-10 15:12:50 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set 4.5.0 [22018-171]
10-10 15:13:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set 4.5.0 [22018-171]
10-10 15:14:10 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4" が見つかりません
Column "4" not found; SQL statement:
update CMN_VER_INFO set "4" + . + "5" + . "0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.readTableColumn(Parser.java:654)
	at org.h2.command.Parser.parseUpdate(Parser.java:688)
	at org.h2.command.Parser.parsePrepared(Parser.java:426)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:14:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "UPDATE CMN_VER_INFO SET VER_VERSION=""4"" + .[*] + ""5"" + . ""0"" "; 期待されるステートメント "SELECT, FROM"
Syntax error in SQL statement "UPDATE CMN_VER_INFO SET VER_VERSION=""4"" + .[*] + ""5"" + . ""0"" "; expected "SELECT, FROM"; SQL statement:
update CMN_VER_INFO set VER_VERSION="4" + . + "5" + . "0" [42001-171]
10-10 15:14:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION="4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:14:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION="4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:15:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION = "4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:18:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "A" が見つかりません
Column "A" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION = a [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:20:32 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set VER_VERSION = 4.5.0 where VER_VERSION=null [22018-171]
10-10 15:20:39 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
update CMN_VER_INFO set VER_VERSION = 4.5.0 [22018-171]
10-10 15:20:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION = "4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:21:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "CMN_VER_VERSION" が見つかりません
Column "CMN_VER_VERSION" not found; SQL statement:
update CMN_VER_INFO set CMN_VER_VERSION = "4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.readTableColumn(Parser.java:654)
	at org.h2.command.Parser.parseUpdate(Parser.java:688)
	at org.h2.command.Parser.parsePrepared(Parser.java:426)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:21:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
update CMN_VER_INFO set VER_VERSION = "4.5.0" [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Update.prepare(Update.java:184)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:23:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: データ変換中にエラーが発生しました "4.5.0"
Data conversion error converting "4.5.0"; SQL statement:
insert into CMN_VER_INFO (VER_VERSION) values (4.5.0) [22018-171]
10-10 15:23:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列 "4.5.0" が見つかりません
Column "4.5.0" not found; SQL statement:
insert into CMN_VER_INFO (VER_VERSION) values ("4.5.0") [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:141)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.engine.Session.prepareCommand(Session.java:366)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:121)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:181)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeUpdate(SqlExecJob.java:341)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:204)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
10-10 15:23:51 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT COUNT(*) FROM PUBLIC.CMN_VER_INFO [50200-171]
10-10 15:23:54 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
DELETE FROM PUBLIC.CMN_VER_INFO WHERE VER_VERSION = ?  [50200-171]
10-10 15:24:03 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
DELETE FROM PUBLIC.CMN_VER_INFO WHERE VER_VERSION = ?  [50200-171]
10-10 15:24:34 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
UPDATE PUBLIC.CMN_VER_INFO SET VER_VERSION= ? WHERE VER_VERSION = ?  [50200-171]
10-10 15:28:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "UPDATE CMN_VER_INFO SER VER_VERSION[*]='4.5.0' "; 期待されるステートメント "SET"
Syntax error in SQL statement "UPDATE CMN_VER_INFO SER VER_VERSION[*]='4.5.0' "; expected "SET"; SQL statement:
update CMN_VER_INFO ser VER_VERSION='4.5.0' [42001-171]
10-10 15:28:42 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT COUNT(*) FROM ( 
select * from CMN_VER_INFO
 ) TBL [50200-171]
10-10 15:32:05 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT COUNT(*) FROM PUBLIC.CMN_VER_INFO [50200-171]
10-10 15:35:08 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: テーブル "CMN_VER_INFO" のロック試行がタイムアウトしました
Timeout trying to lock table "CMN_VER_INFO"; SQL statement:
SELECT COUNT(*) FROM PUBLIC.CMN_VER_INFO [50200-171]
11-20 09:28:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ENQ_ADM_CONF" が見つかりません
Table "ENQ_ADM_CONF" not found; SQL statement:
select * from ENQ_ADM_CONF [42102-171]
11-20 09:29:11 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ENQ_ADM_CONF" が見つかりません
Table "ENQ_ADM_CONF" not found; SQL statement:
SELECT * FROM PUBLIC.ENQ_ADM_CONF LIMIT 501 [42102-171]
08-28 13:36:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: 列名 "FAC_WARN_CNT" が重複しています
Duplicate column name "FAC_WARN_CNT"; SQL statement:
alter table FILE_ACONF add FAC_WARN_CNT integer not null default 0 [42121-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:379)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:554)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:310)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:219)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:155)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at zigen.plugin.db.core.SQLInvoker.execute(SQLInvoker.java:195)
	at zigen.plugin.db.ui.jobs.SqlExecJob.execute(SqlExecJob.java:359)
	at zigen.plugin.db.ui.jobs.SqlExecJob.executeSingleSQL(SqlExecJob.java:201)
	at zigen.plugin.db.ui.jobs.SqlExecJob.run(SqlExecJob.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
